### ISSUE TITLE
Error - [ 96%] Linking CXX executable sanityck

### ISSUE THREAD

**Issue by ampaschoal** [JEMRIS/jemris#1]
Hello,

I'm trying to install jemris on my Ubuntu using cmake. The cmake command was ok, but when I tried the make command I found the following error.

[ 96%] Linking CXX executable sanityck
libcore.a(BinaryContext.cpp.o): In function `BinaryContext::BinaryContext(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, IO::Mode)':
BinaryContext.cpp:(.text+0x228): undefined reference to `vtk__H5check_version'
BinaryContext.cpp:(.text+0x280): undefined reference to `vtk__H5check_version'
BinaryContext.cpp:(.text+0x2e0): undefined reference to `vtk__H5check_version'
BinaryContext.cpp:(.text+0x365): undefined reference to `vtk__H5check_version'
libcore.a(BinaryContext.cpp.o): In function `HDF5IO::FileAccess()':
BinaryContext.cpp:(.text._ZN6HDF5IO10FileAccessEv[_ZN6HDF5IO10FileAccessEv]+0x70): undefined reference to `vtk__H5check_version'
libcore.a(BinaryContext.cpp.o):BinaryContext.cpp:(.text._ZN6HDF5IO10FileAccessEv[_ZN6HDF5IO10FileAccessEv]+0xc8): more undefined references to `vtk__H5check_version' follow
collect2: error: ld returned 1 exit status
src/CMakeFiles/sanityck.dir/build.make:123: recipe for target 'src/sanityck' failed
make[2]: *** [src/sanityck] Error 1
CMakeFiles/Makefile2:89: recipe for target 'src/CMakeFiles/sanityck.dir/all' failed
make[1]: *** [src/CMakeFiles/sanityck.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

Can anybody help me?

**Comment by stoeckert** [comment]
which Ubuntu version are you using and which HDF5 library is installed? 

JEMRIS is tested on 16.04 - I have not yet looked into 18.04.
It needs serial HDF5 (package  libhdf5-serial-dev) and won't compile with parallel HDF5 library. 

Hope this helps!
Tony

**Comment by ampaschoal** [comment]
Apparently there was a wrong path to HDF5 library, now it worked correctly. Thank you!
